return {}
-- return {
--     {
--         "neovim/nvim-lspconfig",
--         opts = {
--             settings = {
--                 typescript = {
--                     format = { enable = false },
--                 },
--                 javascript = {
--                     format = { enable = false },
--                 },
--             },
--         },
--     },
-- }
